[package]
name = "neural_game"
version = "0.1.0"
authors = ["Kiley Owen <yelikdev@gmail.com>"]

[dependencies]
cgmath = "*"
log = "*"
rustc-serialize = "*"
gfx = "*"
gfx_device_gl = "*"
gfx_window_sdl = "*"
gfx_window_glutin = "*"
glutin = "*"
image = "*"
sdl2 = "*"
find_folder = "*"
